### ISSUE TITLE
Create different sections for Student Page 1) study videos,  2) my tutor videos,  3) tutor recommended videos

### ISSUE THREAD

**Issue by ambersu123** [chingu-voyages/v29-toucans-team-01#41]

**Comment by DrewDen** [comment]
This issue has been worked on by Andrew and Tamara.  We created the My study video section and a Tutor Recommended videos section.  It seems that my tutor videos are the same as tutor recommended videos so that part wasn't added.  I believe this would be a good thing to discuss over the meeting today.  Is it important for the MVP?
